config/routes.rb
# frozen_string_literal: true
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  devise_scope :user do
    post 'send_email_confirmation', to: 'omniauth_callbacks#send_email_confirmation',
                                    as: :send_email_confirmation
    get 'email_confirmation/:token', to: 'omniauth_callbacks#email_confirmation',
                                     as: :email_confirmation
  end

  concern :voteable do
    post :like, :dislike, on: :member
  end

  resources :questions do
    concerns :voteable
    resources :answers, except: [:index, :show], shallow: true do
      concerns :voteable
      post :toggle_best, on: :member
      resources :comments, only: [:new, :create, :destroy],
                           defaults: { commentable: 'answer' }
    end
    resources :comments, only: [:new, :create, :destroy], shallow: true,
                         defaults: { commentable: 'question' }
    resources :subscriptions, only: [:create, :destroy], shallow: true
  end

  resources :attachments, only: :destroy
  get '/search', to: 'search#show', as: :search

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end
      resources :questions, only: [:index, :show, :create] do
        resources :answers, only: [:index, :show, :create]
      end
    end
  end

  root to: 'questions#index'

  mount ActionCable.server => '/cable'
end

app/models/question.rb
# frozen_string_literal: true
class Question < ApplicationRecord
  include Voteable
  include Commentable

  has_many :answers, dependent: :destroy
  has_many :attachments, as: :attachable, dependent: :destroy
  has_many :subscriptions, dependent: :destroy
  has_many :subscribers, through: :subscriptions, source: :user

  belongs_to :user

  after_save ThinkingSphinx::RealTime.callback_for(:question)

  validates :title, :body, :user_id, presence: true

  accepts_nested_attributes_for :attachments, allow_destroy: true

  scope :past_day, -> { where(created_at: 1.day.ago.all_day) }

  after_create :subscribe_author

  private

  def subscribe_author
    subscriptions.create(user_id: user.id)
  end
end

app/controllers/api/v1/questions_controller.rb
# frozen_string_literal: true
module Api
  module V1
    class QuestionsController < Api::V1::BaseController
      load_and_authorize_resource

      def index
        respond_with @questions.order(updated_at: :desc)
      end

      def show
        respond_with @question
      end

      def create
        respond_with @question = current_resource_owner.questions.create(question_params)
      end

      private

      def question_params
        params.require(:question).permit(:title, :body)
      end
    end
  end
end

app/controllers/questions_controller.rb
# frozen_string_literal: true
class QuestionsController < ApplicationController
  include Votes

  load_and_authorize_resource

  before_action :authenticate_user!, except: [:index, :show]
  before_action :build_answer, only: :show
  before_action :gon_question, only: :show

  after_action :publish_question, only: [:create]

  respond_to :js

  def index
    respond_with(@questions)
  end

  def show
    @answers = @question.answers.ordered
    @subscription = @question.subscriptions.find_by(user_id: current_user.id) if current_user
    respond_with @question
  end

  def new
    respond_with(@question)
  end

  def create
    respond_with(@question = current_user.questions.create(question_params))
  end

  def update
    respond_with @question.update(question_params)
  end

  def destroy
    respond_with(@question.destroy)
  end

  private

  def question_params
    params.require(:question).permit(:title, :body, attachments_attributes: [:id, :file, :_destroy])
  end

  def build_answer
    @answer = @question.answers.build
  end

  def gon_question
    gon.question_id = @question.id
  end

  def publish_question
    return if @question.errors.any?
    ActionCable.server.broadcast(
      'questions',
      ApplicationController.render(
        partial: 'questions/question',
        locals: { question: @question }
      )
    )
  end
end

app/views/questions/_answers.html.slim
- @answers.each do |answer|
  div id="answer_#{answer.id}"
    = render 'answers/answer', answer: answer, question: @question

app/views/questions/_content.html.slim
- cache [@question, can?(:edit, @question), user_signed_in?] do
  .question-title
    h1= @question.title
    - if user_signed_in?
      .btn-group
        button.btn-link.dropdown-toggle data-toggle="dropdown"
          span.glyphicon.glyphicon-cog.question-settings
        ul.dropdown-menu
          - if can?(:edit, @question)
            li= link_to 'Edit question', edit_question_path(id: @question.id), remote: true
            li= link_to 'Delete question', question_path(@question), method: :delete
          = render 'subscriptions/subscription'
  hr
  .row
    .col-md-1
      = render 'votes/rating', voteable: @question
    .col-md-11
      .lead= @question.body
      = render 'attachments/attachments_list', object: @question
      = render 'comments/comments', commentable: @question

app/views/questions/_form.html.slim
.form-horizontal
  = form_for @question, remote: @question.persisted? do |f|
    - if @question.errors.any?
      #question-errors
        - @question.errors.full_messages.each do |msg|
          .alert.alert-danger= msg
    .form-group
      = f.text_field :title, placeholder: 'Title', class: 'form-control'
    .form-group
      = f.text_area :body, placeholder: 'Your text', rows: 3, class: 'form-control'
    .form-group
      = f.fields_for :attachments, @question.attachments.build do |a|
        = link_to_add_association 'Add files', f, :attachments, class: 'btn btn-xs btn-primary', 
          partial: 'attachments/fields'
    .form-group= f.submit 'Save', class: 'btn btn-success'
    - if block_given?
      .form-group= yield

app/views/questions/_question.html.slim
span= link_to question.title, question_path(question), class: 'media-heading'

app/views/questions/edit.js.erb
$('#question_<%= @question.id %>').html("<%= j render 'questions/form' %>");

app/views/questions/index.html.slim
.page-header
  h1= 'Questions'

ul.list-group.questions-list
  - cache collection_cache_key_for :question do
    - @questions.each do |question|
      li.list-group-item
        = render 'question', question: question
        span.badge.badge-votes= "#{question.rating.to_i} votes"
        span.badge.badge-answers= "#{question.answers.count} answers"

app/views/questions/new.html.slim
h3= "New question"

.col-md-6
  = render 'form' do
    = link_to 'Back', root_path, class: 'btn btn-default'

app/views/questions/show.html.slim
- cache @question do
  div id="question_#{@question.id}"
    = render 'content', question: @question

  h4#answers_count= "#{@question.answers.count} Answers"
  hr

  .answers
    = render 'answers'

  .answer_form
    - if can?(:create, Answer)
      = render 'answers/form'
    - else
      = 'You need to sign in or sign up before continuing.'

app/views/questions/update.js.erb
<% if @question.valid? %>
  $('#question_<%= @question.id %>').html("<%= j render 'questions/content', question: @question %>");
  $('#question-errors').html('');
<% else %>
  $('#question_<%= @question.id %>').html("<%= j render 'questions/form' %>");
<% end %>