config/routes.rb
# frozen_string_literal: true
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  devise_scope :user do
    post 'send_email_confirmation', to: 'omniauth_callbacks#send_email_confirmation',
                                    as: :send_email_confirmation
    get 'email_confirmation/:token', to: 'omniauth_callbacks#email_confirmation',
                                     as: :email_confirmation
  end

  concern :voteable do
    post :like, :dislike, on: :member
  end

  resources :questions do
    concerns :voteable
    resources :answers, except: [:index, :show], shallow: true do
      concerns :voteable
      post :toggle_best, on: :member
      resources :comments, only: [:new, :create, :destroy],
                           defaults: { commentable: 'answer' }
    end
    resources :comments, only: [:new, :create, :destroy], shallow: true,
                         defaults: { commentable: 'question' }
    resources :subscriptions, only: [:create, :destroy], shallow: true
  end

  resources :attachments, only: :destroy
  get '/search', to: 'search#show', as: :search

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end
      resources :questions, only: [:index, :show, :create] do
        resources :answers, only: [:index, :show, :create]
      end
    end
  end

  root to: 'questions#index'

  mount ActionCable.server => '/cable'
end

app/models/comment.rb
# frozen_string_literal: true
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true, touch: true
  belongs_to :user

  after_save ThinkingSphinx::RealTime.callback_for(:comment)

  validates :body, presence: true

  def question
    return commentable if commentable.is_a?(Question)
    commentable.question
  end
end

app/controllers/comments_controller.rb
# frozen_string_literal: true
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_commentable, except: :destroy
  after_action :publish_comment, only: :create

  respond_to :js

  load_resource only: :destroy
  authorize_resource

  def new
    respond_with(@comment = @commentable.comments.new)
  end

  def create
    @comment = @commentable.comments.create(
      comment_params.merge(user_id: current_user.id)
    )
    respond_with(@comment)
  end

  def destroy
    respond_with(@comment.destroy)
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end

  def set_commentable
    @commentable = params[:commentable].classify.constantize.find(commentable_id)
  end

  def commentable_id
    params[(params[:commentable].singularize + '_id').to_sym]
  end

  def publish_comment
    return if @comment.errors.any?

    ActionCable.server.broadcast(
      "comments-question-#{@comment.question.id}",
      comment: @comment,
      commentable: { class: @commentable.class.name, id: @commentable.id }
    )
  end
end

app/helpers/comments_helper.rb
# frozen_string_literal: true
module CommentsHelper
end

app/views/comments/_comment.html.slim
- cache [comment, can?(:destroy, comment)] do
  hr
  span= comment.body
  - if can?(:destroy, comment)
    = link_to comment_path(comment), remote: true, method: :delete, title: 'Delete', class: 'btn btn-xs' do
      span.glyphicon.glyphicon-trash

app/views/comments/_comments.html.slim
.comments id="comments-#{commentable.class.name}-#{commentable.id}"
  .comments-list
    - commentable.comments.each do |comment|
      .comment id="comment-#{commentable.class.name}-#{comment.id}"
        = render 'comments/comment', comment: comment, commentable: commentable
  - if can?(:create, Comment)
    = link_to 'Add a comment', new_polymorphic_path([commentable, Comment]), remote: true, class: 'btn btn-xs btn-default'

app/views/comments/_form.html.slim
= form_for [@comment.commentable, @comment], remote: true, html: { class: 'form-horizontal' } do |f|
  - if @comment.errors.any?
    #comment-errors
      - @comment.errors.full_messages.each do |msg|
        .alert.alert-danger= msg

  .form-group
    .col-sm-5
      = f.text_area :body, placeholder: 'Your comment', rows: 3, class: 'form-control'
  .form-group
    .col-sm-10
      = f.submit 'Save', class: 'btn btn-success'

app/views/comments/create.js.erb
<% if @comment.valid? %>
  $('#new_comment').remove();
  $('#comments-<%= @commentable.class.name %>-<%= @commentable.id %> .comments-list').append(
    "<div id='comment-<%= @commentable.class.name %>-<%= @comment.id %>'>" +
      "<%= j render 'comments/comment', comment: @comment, commentable: @commentable %>" +
    "</div>"
  );
  $('#comment-errors').html('');
<% else %>
  $('#comments-<%= @commentable.class.name %>-<%= @commentable.id %>').html(
    "<%= j render 'comments/form' %>"
  );
<% end %>

app/views/comments/destroy.js.erb
$('#comment-<%= @comment.commentable.class.name %>-<%= @comment.id %>').remove();

app/views/comments/new.js.erb
if ($('#new_comment').length > 0)
  $('#new_comment').remove();
else
  $('#comments-<%= @commentable.class.name %>-<%= @commentable.id %>').append(
    "<%= j render 'comments/form', commentable: @commentable, comment: @comment %>"
  );