config/routes.rb
# frozen_string_literal: true
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  devise_scope :user do
    post 'send_email_confirmation', to: 'omniauth_callbacks#send_email_confirmation',
                                    as: :send_email_confirmation
    get 'email_confirmation/:token', to: 'omniauth_callbacks#email_confirmation',
                                     as: :email_confirmation
  end

  concern :voteable do
    post :like, :dislike, on: :member
  end

  resources :questions do
    concerns :voteable
    resources :answers, except: [:index, :show], shallow: true do
      concerns :voteable
      post :toggle_best, on: :member
      resources :comments, only: [:new, :create, :destroy],
                           defaults: { commentable: 'answer' }
    end
    resources :comments, only: [:new, :create, :destroy], shallow: true,
                         defaults: { commentable: 'question' }
    resources :subscriptions, only: [:create, :destroy], shallow: true
  end

  resources :attachments, only: :destroy
  get '/search', to: 'search#show', as: :search

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end
      resources :questions, only: [:index, :show, :create] do
        resources :answers, only: [:index, :show, :create]
      end
    end
  end

  root to: 'questions#index'

  mount ActionCable.server => '/cable'
end

app/models/answer.rb
# frozen_string_literal: true
class Answer < ApplicationRecord
  include Voteable
  include Commentable

  belongs_to :question, touch: true
  belongs_to :user

  has_many :attachments, as: :attachable, dependent: :destroy

  after_save ThinkingSphinx::RealTime.callback_for(:answer)

  validates :body, :question_id, :user_id, presence: true

  accepts_nested_attributes_for :attachments, allow_destroy: true

  scope :best_answers_except, ->(answer) { where(best: true).where.not(id: answer.id) }
  scope :ordered, -> { order(best: :desc, created_at: :asc) }

  after_commit :send_subscription, on: :create

  def toggle_best
    with_lock do
      question.answers.update_all(best: false)
      self.best = !best
      save
    end
  end

  private

  def send_subscription
    QuestionSubscriptionJob.perform_later(question, self)
  end
end

app/controllers/answers_controller.rb
# frozen_string_literal: true
class AnswersController < ApplicationController
  include Votes

  before_action :authenticate_user!

  after_action :publish_answer, only: [:create]

  respond_to :js

  load_resource :question
  load_and_authorize_resource :answer, through: :question, shallow: true,
                                       only: [:create, :edit, :update, :destroy, :toggle_best]

  def create
    @answer = current_user.answers.create(
      answer_params.merge(question_id: @question.id)
    )
    respond_with(@answer)
  end

  def update
    respond_with @answer.update(answer_params)
  end

  def destroy
    respond_with(@answer.destroy)
  end

  def toggle_best
    respond_with(@answer.toggle_best)
  end

  private

  def answer_params
    params.require(:answer).permit(:body, attachments_attributes: [:id, :file, :_destroy])
  end

  def can_manage_answer?
    @answer.user_id == current_user.id
  end

  def publish_answer
    return if @answer.errors.any?

    ActionCable.server.broadcast(
      "answer_question_#{@question.id}",
      answer: AnswerSerializer.new(@answer),
      question: QuestionSerializer.new(@question),
      attachments: ActiveModel::Serializer::CollectionSerializer.new(@answer.attachments)
    )
  end
end

app/controllers/api/v1/answers_controller.rb
# frozen_string_literal: true
module Api
  module V1
    class AnswersController < Api::V1::BaseController
      load_and_authorize_resource

      def index
        respond_with @answers
      end

      def show
        respond_with @answer
      end

      def create
        @answer = current_resource_owner.answers.create(
          answer_params.merge(question_id: params[:question_id])
        )
        respond_with @answer
      end

      private

      def answer_params
        params.require(:answer).permit(:body)
      end
    end
  end
end

app/helpers/answers_helper.rb
# frozen_string_literal: true
module AnswersHelper
  def toggle_best_link(answer)
    link_to toggle_best_answer_path(id: answer.id), method: :post, remote: true, class: 'btn',
                                                    id: "toggle_best_#{answer.id}" do
      content_tag(:span, nil, class: "glyphicon glyphicon-ok #{'selected' if answer.best}")
    end
  end
end

app/views/answers/_answer.html.slim
- cache [answer, can?(:edit, answer), user_signed_in?] do
  .row
    .col-md-1
      = render 'votes/rating', voteable: answer
      - if can?(:toggle_best, answer)
        .toggle-best= toggle_best_link(answer)
      - elsif answer.best
        .toggle-best
          .glyphicon.glyphicon-ok.selected
    .col-md-11
      - if can?(:edit, answer)
        .btn-group
          = link_to edit_answer_path(id: answer.id), remote: true, class: 'btn btn-xs', title: 'Edit' do
            span.glyphicon.glyphicon-pencil
          = link_to answer_path(id: answer.id), remote: true, method: :delete, title: 'Delete', class: 'btn btn-xs' do
            span.glyphicon.glyphicon-trash

      p= answer.body
      = render 'attachments/attachments_list', object: answer
      = render 'comments/comments', commentable: answer
  hr

app/views/answers/_form.html.slim
= form_for shallow_args(@question, @answer), remote: true, html: { class: 'form-horizontal' } do |f|
  - if @answer.errors.any?
    #answer-errors
      - @answer.errors.full_messages.each do |msg|
        .alert.alert-danger= msg

  .col-sm-5
    .form-group
      = f.text_area :body, placeholder: 'Your answer', rows: 3, class: 'form-control'
    .form-group
      = f.fields_for :attachments, @answer.attachments.build do |a|
        = link_to_add_association 'Add files', f, :attachments, class: 'btn btn-xs btn-primary',
          partial: 'attachments/fields'
    .form-group
      = f.submit 'Save', class: 'btn btn-success'

app/views/answers/create.js.erb
<% if @answer.valid? %>
  $('.answers').append(
    "<div id='answer_<%= @answer.id %>'>" +
      "<%= j render 'answers/answer', answer: @answer, question: @question %>" +
    "</div>"
  );
  $('#answer_body').val('');
  $('#answer-errors').html('');
  $('.nested-fields').remove();
  $("#answers_count").html("<%= @question.answers.count %> Answers");
<% else %>
  $('.answer_form').html("<%= j render 'answers/form' %>")
<% end %>

app/views/answers/destroy.js.erb
$("#answers_count").html("<%= @answer.question.answers.size %> Answers");
$('#answer_<%= @answer.id %>').remove();

app/views/answers/edit.js.erb
$('.answer_form').remove();
$('#answer_<%= @answer.id %>').html("<%= j render 'answers/form' %>");

app/views/answers/toggle_best.js.erb
$('.answers span').removeClass('selected');
$("#toggle_best_<%= @answer.id %>").replaceWith("<%= j toggle_best_link(@answer) %>");

app/views/answers/update.js.erb
<% if @answer.valid? %>
  $('#answer_<%= @answer.id %>').html("<%= j render 'answers/answer', answer: @answer, question: @answer.question %>");
  $('#answer-errors').html('');
<% else %>
  $('#answer_<%= @answer.id %>').html("<%= j render 'answers/form' %>");
<% end %>