config/routes.rb
# frozen_string_literal: true
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  devise_scope :user do
    post 'send_email_confirmation', to: 'omniauth_callbacks#send_email_confirmation',
                                    as: :send_email_confirmation
    get 'email_confirmation/:token', to: 'omniauth_callbacks#email_confirmation',
                                     as: :email_confirmation
  end

  concern :voteable do
    post :like, :dislike, on: :member
  end

  resources :questions do
    concerns :voteable
    resources :answers, except: [:index, :show], shallow: true do
      concerns :voteable
      post :toggle_best, on: :member
      resources :comments, only: [:new, :create, :destroy],
                           defaults: { commentable: 'answer' }
    end
    resources :comments, only: [:new, :create, :destroy], shallow: true,
                         defaults: { commentable: 'question' }
    resources :subscriptions, only: [:create, :destroy], shallow: true
  end

  resources :attachments, only: :destroy
  get '/search', to: 'search#show', as: :search

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end
      resources :questions, only: [:index, :show, :create] do
        resources :answers, only: [:index, :show, :create]
      end
    end
  end

  root to: 'questions#index'

  mount ActionCable.server => '/cable'
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Qna
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = action_cable_meta_tag
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = Gon::Base.render_data
  body
    .navbar.navbar-default
      .collapse.navbar-collapse
        ul.nav.navbar-nav
          li= link_to 'Home', questions_path
          - if current_user
            li= link_to 'Ask question', new_question_path
            li= link_to 'Log out', destroy_user_session_path, method: :delete
          - else
            li= link_to 'Sign in', new_user_session_path
            li= link_to 'Sign up', new_user_registration_path
        = form_tag search_path, method: :get, class: 'navbar-form navbar-right search form-inline' do
          .form-group
            = text_field_tag :search_query, params[:search_query], placeholder: 'Search', class: 'form-control'
            = select_tag :search_entity, options_for_select(search_entities_collection, params[:search_entity]),
                                         prompt: '-- All --', class: 'selectpicker form-control'
          = submit_tag 'Search', class: 'btn btn-default'
    = bootstrap_flash
    .container
      = yield